/**
 * Build the public API surface for backwards compatibility.
 */
export function createPublicApi(deps = {}) {
    const {
        open,
        closeModal,
        rollbackToHistory,
        AppState,
        getAllVolumesWorldbook,
        saveTaskState,
        loadTaskState,
        exportSettings,
        importSettings,
        handleRerollMemory,
        handleRerollSingleEntry,
        retryChapterAssetsPolish,
        useLocalPresplitFallback,
        findEntrySourceMemories,
        showRerollEntryModal,
        showBatchRerollModal,
        showRollHistorySelector,
        importAndMergeWorldbook,
        setCategoryLightState,
        rebuildWorldbookFromMemories,
        applyDefaultWorldbookEntries,
        callCustomAPI,
        callSillyTavernAPI,
        showConsolidateCategorySelector,
        showAliasMergeUI,
        showManualMergeUI,
        getEnabledCategories,
        rechunkMemories,
        showSearchModal,
        showReplaceModal,
        getEntryConfig,
        setEntryConfig,
        setCategoryDefaultConfig,
        MemoryHistoryDB,
    } = deps;

    return {
        open,
        close: closeModal,
        _rollbackToHistory: rollbackToHistory,
        getWorldbook: () => AppState.worldbook.generated,
        getMemoryQueue: () => AppState.memory.queue,
        getVolumes: () => AppState.worldbook.volumes,
        getAllVolumesWorldbook,
        saveTaskState,
        loadTaskState,
        exportSettings,
        importSettings,
        getParallelConfig: () => AppState.config.parallel,
        handleRerollMemory,
        handleRerollSingleEntry,
        retryChapterAssetsPolish,
        useLocalPresplitFallback,
        findEntrySourceMemories,
        showRerollEntryModal,
        showBatchRerollModal,
        showRollHistory: showRollHistorySelector,
        importAndMerge: importAndMergeWorldbook,
        getCategoryLightSettings: () => AppState.config.categoryLight,
        setCategoryLight: setCategoryLightState,
        rebuildWorldbook: rebuildWorldbookFromMemories,
        applyDefaultWorldbook: applyDefaultWorldbookEntries,
        getSettings: () => AppState.settings,
        callCustomAPI,
        callSillyTavernAPI,
        showConsolidateCategorySelector,
        showAliasMergeUI,
        showManualMergeUI,
        getCustomCategories: () => AppState.persistent.customCategories,
        getEnabledCategories,
        getChapterRegexSettings: () => AppState.config.chapterRegex,
        rechunkMemories,
        showSearchModal,
        showReplaceModal,
        getEntryConfig,
        setEntryConfig,
        setCategoryDefaultConfig,
        getDefaultWorldbookEntriesUI: () => AppState.persistent.defaultEntries,
        getEntryRollHistory: (cat, entry) => MemoryHistoryDB.getEntryRollResults(cat, entry),
        clearEntryRollHistory: (cat, entry) => MemoryHistoryDB.clearEntryRollResults(cat, entry),
        exportTaskState: saveTaskState,
        importTaskState: loadTaskState,
        rerollMemory: handleRerollMemory,
        rerollSingleEntry: handleRerollSingleEntry,
        retryChapterAssetsPolish,
        useLocalPresplitFallback,
    };
}
